Musica\TodoBundle\Entity\Albums:
    type: entity
    table: albums
    indexes:
        fk_albums_artistas1_idx:
            columns:
                - artistas_ar_id
    id:
        alId:
            type: integer
            nullable: false
            unsigned: false
            comment: Identificacdor
            id: true
            column: al_id
            generator:
                strategy: IDENTITY
    fields:
        alNombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Nombre del album'
            column: al_nombre
        alAnio:
            type: string
            nullable: true
            length: 5
            fixed: true
            comment: 'Anio de lanzamineto del album. Nota: solo se neceita a manera de string'
            column: al_anio
    manyToOne:
        artistasAr:
            targetEntity: Artistas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                artistas_ar_id:
                    referencedColumnName: ar_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
