Musica\TodoBundle\Entity\Artistas:
    type: entity
    table: artistas
    id:
        arId:
            type: integer
            nullable: false
            unsigned: false
            comment: Identificacdor
            id: true
            column: ar_id
            generator:
                strategy: IDENTITY
    fields:
        arNombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Nombre del artista o banda dueña de varios albums'
            column: ar_nombre
    lifecycleCallbacks: {  }
