Musica\TodoBundle\Entity\Artistas:
    type: entity
    table: musica.artistas
    id:
        arId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: ar_id
            generator:
                strategy: SEQUENCE
    fields:
        arNombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Nombre del grupo musical o artista dueño de varios albums'
            column: ar_nombre
    lifecycleCallbacks: {  }
