Musica\TodoBundle\Entity\Binarios:
    type: entity
    table: musica.binarios
    repositoryClass: Musica\TodoBundle\Entity\BinariosRepository
    indexes:
        IDX_BFDF38C4DADE7FBA:
            columns:
                - albums_al_id
    id:
        biId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: bi_id
            generator:
                strategy: SEQUENCE
    fields:
        biNombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Nombre del archivo de imagen'
            column: bi_nombre
        biTamanioBytes:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: 'Tamanio de la imagen en bytes'
            column: bi_tamanio_bytes
        biBin:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Informacion binaria del archivo de imagen'
            column: bi_bin
        biExtension:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Extention de la imagen'
            column: bi_extension
        biRuta:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Ruta donde se ubica de forma fisica el archivo'
            column: bi_ruta
    manyToOne:
        albumsAl:
            targetEntity: Albums
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                albums_al_id:
                    referencedColumnName: al_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
