Musica\TodoBundle\Entity\Covers:
    type: entity
    table: covers
    indexes:
        IDX_F08DF1B2DADE7FBA:
            columns:
                - albums_al_id
    id:
        coId:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: co_id
            generator:
                strategy: SEQUENCE
    fields:
        coNombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Nombre del archivo de imagen'
            column: co_nombre
        coTamanio:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            comment: 'Tamanio de la imagen en bytes'
            column: co_tamanio
        coBin:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: 'Informacion binaria del archivo de imagen'
            column: co_bin
        coExtension:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Extention de la imagen'
            column: co_extension
    manyToOne:
        albumsAl:
            targetEntity: Albums
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                albums_al_id:
                    referencedColumnName: al_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
