Musica\TodoBundle\Entity\Tracks:
    type: entity
    table: tracks
    indexes:
        fk_tracks_albums_idx:
            columns:
                - albums_al_id
    id:
        trId:
            type: integer
            nullable: false
            unsigned: false
            comment: Identificacdor
            id: true
            column: tr_id
            generator:
                strategy: IDENTITY
    fields:
        trNombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Nombre de la cancion'
            column: tr_nombre
        trLongitud:
            type: string
            nullable: true
            length: 5
            fixed: true
            comment: 'Longitud de la cancion. Nota: solo se neceita a manera de string'
            column: tr_longitud
    manyToOne:
        albumsAl:
            targetEntity: Albums
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                albums_al_id:
                    referencedColumnName: al_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
