parameters:
    database_driver: pdo_pgsql
    database_host: 172.16.6.123
    database_port: '5432'
    database_name: musica
    database_user: postgres
    database_password: postgres
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 87c2caa90aac8ba05e1c2cff5fe33522
    database_path: null
